wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    code_path: code/research_code/DQfD_train.py
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1633761891
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      4: 3.9.6
      5: 0.12.4
      8:
      - 5
