name: minerl
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python
  - pip
  - py-opencv
  - cudatoolkit=11.1
  - cudatoolkit-dev=11.1
  - pytorch=1.9.0=py3.9_cuda11.1_cudnn8.0.5_0
  - torchvision
  - pip:
    - crowdai_api
    - minerl
    - coloredlogs
    - matplotlib
    - pyro4
    - deepspeed
