name: minerl
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python
  - pip
  - py-opencv
  - cudatoolkit=11.1
  - pytorch=1.9.0
  - torchvision
  - pip:
    - crowdai_api
    - minerl
    - coloredlogs
    - matplotlib
    - pyro4
