wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    code_path: code/research_code/DQfD_train.py
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1635034360
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 15
      - 16
      4: 3.9.6
      5: 0.12.4
      8:
      - 5
dynamics_model_cls:
  desc: null
  value: null
env_name:
  desc: null
  value: MineRLNavigateDenseVectorObf-v0
epsilon:
  desc: null
  value: 0.05
model_path:
  desc: null
  value: /home/lieberummaas/datadisk/minerl/run_logs/DQfD_pretraining/169ajjs0/checkpoints/last.ckpt
seed:
  desc: null
  value: 2
visual_model_cls:
  desc: null
  value: ConvFeatureExtractor
