wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    code_path: code/research_code/train_VAE.py
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: Training/loss
      5: 1
      6:
      - 1
    - 1: Training/recon_loss
      5: 1
      6:
      - 1
    - 1: Training/latent_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: Reconstruction._type
      5: 1
      6:
      - 1
    - 1: Reconstruction.path
      5: 1
      6:
      - 1
    - 1: Reconstruction.sha256
      5: 1
      6:
      - 1
    - 1: Reconstruction.size
      5: 1
      6:
      - 1
    - 1: Reconstruction.format
      5: 1
      6:
      - 1
    - 1: Reconstruction.width
      5: 1
      6:
      - 1
    - 1: Reconstruction.height
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1633623977
    t:
      1:
      - 1
      - 9
      3:
      - 16
      4: 3.9.6
      5: 0.12.4
      8:
      - 5
beta:
  desc: null
  value: 1
decoder_kwargs/latent_dim:
  desc: null
  value: 1024
decoder_kwargs/n_hid:
  desc: null
  value: 64
decoder_kwargs/n_init:
  desc: null
  value: 64
encoder_kwargs/latent_dim:
  desc: null
  value: 1024
encoder_kwargs/n_hid:
  desc: null
  value: 64
env_name:
  desc: null
  value: MineRLNavigateDenseVectorObf-v0
latent_dim:
  desc: null
  value: 1024
learning_rate:
  desc: null
  value: 0.0003
